"""add description t to Pattern table

Revision ID: 816c2844529b
Revises: 2512b188bf3a
Create Date: 2019-12-04 05:19:18.560892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816c2844529b'
down_revision = '2512b188bf3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pattern', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pattern', 'description')
    # ### end Alembic commands ###
